### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Goatmaster** [LennyHirsch/PHatBinaryClock#1]
Hey I treid to run the Code but I get an error from python.

Traceback (most recent call last):
  File "binaryClock.py", line 8, in <module>
    from pytz import timezone
ImportError: No module named pytz

**Comment by LennyHirsch** [comment]
@Goatmaster pytz isn't included in the standard python library; you'll have to install it yourself.
Installation instructions and documentation can be found [here](http://pytz.sourceforge.net/).

Hopefully that solves your problem!
